export const availableFurnishings = [
    { name: 'Fan', icon: 'FanIcon' },
    { name: 'Light', icon: 'LightIcon' },
    { name: 'AC', icon: 'AcUnitIcon' },
    { name: 'Wardrobe', icon: 'WardrobeIcon' },
    { name: 'TV', icon: 'TvIcon' },
    { name: 'Bed', icon: 'BedIcon' },
    { name: 'Geyser', icon: 'GeyserIcon' },
    { name: 'Washing Machine', icon: 'WashingMachineIcon' },
    { name: 'Sofa', icon: 'SofaIcon' },
    { name: 'Fridge', icon: 'FridgeIcon' },
    { name: 'Water Purifier', icon: 'WaterDropIcon' },
    { name: 'Stove', icon: 'StoveIcon' },
    { name: 'Chimney', icon: 'ChimneyIcon' },
    { name: 'Microwave', icon: 'MicrowaveIcon' },
    { name: 'Dining Table', icon: 'RestaurantIcon' },
    { name: 'Modular Kitchen', icon: 'KitchenIcon' },
];

export const availableAmenities = [
    { name: 'Power Backup', icon: 'BoltIcon' },
    { name: 'Swimming Pool', icon: 'PoolIcon' },
    { name: 'Gym', icon: 'GymIcon' },
    { name: 'Lift', icon: 'LiftIcon' },
    { name: 'Intercom', icon: 'PhoneIcon' },
    { name: 'Garden', icon: 'GardenIcon' },
    { name: 'Sports Facility', icon: 'TennisIcon' },
    { name: 'Kids Area', icon: 'KidsAreaIcon' },
    { name: 'CCTV', icon: 'CctvIcon' },
    { name: 'Gated Community', icon: 'GateIcon' },
    { name: 'Club House', icon: 'BuildingIcon' },
    { name: 'Community Hall', icon: 'BuildingIcon' },
    { name: 'Regular Water Supply', icon: 'WaterDropIcon' },
    { name: 'Yoga/Meditation Hall', icon: 'SpaIcon' },
    { name: 'Badminton Court', icon: 'TennisIcon' },
    { name: 'Basketball Court', icon: 'CricketIcon' },
    { name: 'Library', icon: 'BuildingIcon' },
    { name: 'Fire Safety', icon: 'ShieldCheckIcon' },
    { name: '24/7 Water Supply', icon: 'WaterDropIcon' },
    { name: 'Amphitheater', icon: 'TheaterIcon' },
    { name: 'Party Hall', icon: 'LoungeIcon' },
    { name: 'Indoor Games', icon: 'SparklesIcon' },
    { name: 'Jogging Track', icon: 'MapIcon' },
];